# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
services:
  - docker

language: go
go:
  - 1.8

env:
  global:
  # GITHUB_USER
  - secure: "Wm9n1YY2NovdTeZZxhkN8rKkojW72KDAmoeRnD1bCJHpPURkfIoe9CrbotTjBbBN28ISplErUhZESMINe5FAPgxrsF+AEpgPuyXH/WVZrxhj+1bM3xtfCiPj9PAkLBOibe9DPTs8G/5q4g8JVoXZZEyFbKai8BGl/bGYXTEsMh+Ew41HHjHa8bjNDoQds9MB3cNW7OxsM1kic11mtLLdfChBDjiNnxH0VUIlnYy1rObRlr6aUljKGj2ykK3MghoE+wt3HM0a7v+57Q4LlRhQggKIfhGfCXcZRao5ZvE+1hnPl3WFGAgltiu8+3uMzyqKNixr/osQvzcuummrLfWizorNsTBRgqw+l6KGkup7x6NE5KTXLmQr5V7ONUWwUk10KEYd9g8V9SOTdbh5I1n4UHRzeYjsK4hYKZpuwzcWHRcAbPbP6e9930Onsjom8Cypl/pjoSUxDQqBAOwcfcCFEotzS2doDI7RrReN6BKndEBlp6hflUoNVgIw8Xl8YmNsXvGBZ2BEZMy1OAt4ptwP+98QqxjLRSfzDcRMaVmHuc6WMQZYimP8bszVBWq2EerhIvNmk3F6LXuYwQRNL1ZOyIuC1TVfeUHHYawROTzX/sB+gectt/9BybZ2/L+VxlbPvZQLxMPmnUDNmKNUUvDjGoZ8+Ju4mUOFjr4uaTNSC5s="
  # GITHUB_AUTH_TOKEN
  - secure: "sp4jsbv8oxcGnNkdH2SEA2V/8v0Y2Bgn8eveBnjc6j/PD8eB775UVBvpd+gw57TZdtssSLunIXepxU4VldEMPNYPv0NaCFKrgfg9qJhVpOnIm86wRhI+6IL05e5OZ0vPnyGzcUNAVugpCEfwzUr2fETWOlTcZ7QebiA8gYY1agkNIUla27Ox9m6bkDglZc6rIVyD2kmSKRUojQaZ6w6jO30q5aC4e7hEde7pPQGxoMG8XH2YUH1mzhIMORsBnUvXF4LALsyFCefta/D8SfoKmwH/4XVzBDcIPnw/d0jtjO+WU+y8wFmaKmkkf/zIBj5MI3OyGH36uMoqCgW8wTkZjctZl23DEeCkQ2b/oDfOIzqKr7M+MsAKnIJWUB0o1kPD2kjDjORnUxcY5/+wPu+54L0q2Ifq+6dHakdzjc5uW+1xVDzGUP8YGdrkzRgDIvwjK3I5F1rfBj7Nfn0t7jNwChwLOWGzgiWhM0Pi531yYDdaxM/VaKC3FKCJS65z9QBnjPUXkkx7y0Q2wet+uV41udAxi5eWgTpRG2zHwKPael3Dae5FBfAhgBzAzx0AVyll+OHBm/brTwPioqvg+2bGDx0UUxnRkzHSfSCvv9l2Iv9nVLkWCNlF9WdEQs09qPvHl1JxSOROsr8VPdKI9I2ZRcKp8ZQenoAPOI2LfmgvwQk="
  # BOOTERY_URL
  - secure: "rFm/EOvJRU+zvG7nliwcuQRTP3ubQaCGuzH+vZrTAKeif7wGSmVK/6694Lyq2GTJz+y4Lrl1mbTy2tq9qDJ0dXWJi129Am4RLm6DUfeQFm/trhvs33VdkIX+2v4hx0pRwomWLU5Db1n6mPMskZqSATkil7KgnO+ePzcGCBiMo5NrWMQeKGg1Vvd01lBga3tcANgVP3EYjppY3nxCPKv0jzCye6gE586j8vm+DeYHQlsPv+gQCuzomYcO1I8j63wZO06jH18pJwlJTL/mVCEw5T2GWZBf2XpE/BkJ3qI1d2/TrH4nIt0sFV58wu5JrpVnNIk1K7+eyt92ha57gLkH7dHyP5qHzbzhCBedc+sSD5W6tAhu7vQdVVWhtQ0qRXSulrX1fcgNauPl6sQnHLrfMdPVNuaRYH2AeyS8/QiL1xXKL4dblIBvAQsMqjTAEV8tcVv+Fb1keBuodpOommDwYJSY9qztczyLEfSsL2eh6tRTojmG04Ex0AFTHZb9nIu4o+CSt0/zXDfHQYJIItu310E1gkijBsCsyLllfyoj+bW9EqeVFCaQnEvKRS/DEuRz/BHGTW34MVWScVujttRcurX1zOjDjMcv5e5Tt4Jm+Q+0OJOPTkp5aJTxXjtWkvCFI2UgJByJAQ6cIocviKYc/lj9KxBhLPQW5kq3fLLKYMQ="

script:
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || go get -u github.com/gokrazy/autoupdate/cmd/... github.com/gokrazy/tools/cmd/gokr-packer'
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || gokr-boot -require_label=please-boot -set_label=please-merge -bootery_url=$BOOTERY_URL || travis_terminate $?'
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || { gokr-merge -require_label=please-merge; ret=$?; if [ $ret -eq 0 ]; then travis_terminate 0; elif [ $ret -eq 1 ]; then travis_terminate 1; else true; fi; }'
  # rebuild kernel
  - go install ./cmd/gokr-rebuild-kernel
  - gokr-rebuild-kernel
  # update pull request
  - '[ "$TRAVIS_SECURE_ENV_VARS" != "true" ] || (go get -u github.com/gokrazy/autoupdate/cmd/gokr-amend && gokr-amend -set_label=please-boot *.dtb vmlinuz)'
